### ISSUE TITLE
Use strawberry perl's structured data

### ISSUE THREAD

**Issue by dnmfarrell** [dnmfarrell/berrybrew#21]
strawberryperl.com now provides a structured JSON description of the available Perls: http://strawberryperl.com/releases.json

This ticket is to convert berrybrew to use it,

cc @stevieb9

**Comment by dnmfarrell** [comment]
Original strawberry perl issue: https://github.com/StrawberryPerl/strawberryperl.com/issues/6

**Comment by stevieb9** [comment]
This is fantastic! Thanks for pointing it out. I will do some due diligence and research, and apply as necessary.

As may be known, I had converted "perls available" to JSON some time ago, so this should slide right in.

**Comment by stevieb9** [comment]
I will keep track of this work in [this issue](https://github.com/stevieb9/berrybrew/issues/62). I've just set up a new devel/test platform for berrybrew (ironically) today, that'll test across numerous platforms constantly instead of one-offs.

Once I get things stable with the implementation of this new change, I will email you personally with what I've done, some briefed test results, and we can go from there.

**Comment by stevieb9** [comment]
The core of this functionality is now in place, and both your repo and mine are up to date at version 1.12.

- new feature `berrybrew fetch`. This is a manual process that pulls down the file, pulls out what we need, and populates the local perls.json file. I didn't want a user to have to require Internet access to list available Perls
- new function, PerlUpdateAvailableList() which does the actual work
- this feature lists in `berrybrew available` only the most current point versions of the major releases
- if the user currently has older versions installed that aren't listed with `fetch`, we register those versions as 'custom' so that they will still be manageable with berrybrew as opposed to being orphan installs
- changed slightly `berrybrew upgrade`. We now only restore the `perls_custom.json` file as opposed to all config files. If the user had any modifications to the default configs, they will have to merge the changes from those files into the new configs in `data/`, using the backups automatically saved during the upgrade process

There's more to come. I am going to adjust things so we can use the releases.json directly. Currently, I extract out the needed data, then write it into a custom local JSON file. To achieve this, I need to make significant changes to the StrawberryPerl class/objects, but for now, it works well
