### ISSUE TITLE
config fails

### ISSUE THREAD

**Issue by garfieldnate** [dnmfarrell/berrybrew#6]
Just downloaded Berrybrew and did `berrybrew config`. It came back with this:

```
C:\dev\berrybrew-3-10-2015\bin>berrybrew config
This is berrybrew, version 0.07
Would you like to add berrybrew to your user PATH? y/n [n] y
Error adding berrybrew to the user PATH
```

I tried again in an admin CMD window, but got the same result. I'm using the current latest Berrybrew, Windows 8/Japanese.

**Comment by hraharahra** [comment]
I found the problem, but util it's fixed properly as a quick workaround you can (copy, move, rename, berrybrew.exe directory to `berrybrew\bin` from `berrybrew-3-10-2015\bin`. I am experiencing the same issue, as I am using it from `berrybrew-master`. Berrybrew path is still appended to your %PATH% variable, despite the error message. you can check it with `echo %PATH%` 
This pollution of the PATH should be harmless AFAIK, but it is preferable to be cleaned.
From current issues and enhancements this requires the least amount of coding, so probably will be fixed sooner:tm: rather than later :pray:
